


name: C Build

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
        
    - name: Build
      run: gcc -o xadrez main.c src/pecas/torre.c src/pecas/bispo.c src/pecas/rainha.c src/tabuleiro/tabuleiro.c -I.
      
    - name: Test run
      run: ./xadrez
