name: "Issue Labeler"
on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.ACTIONS_TOKEN }}"
          sync-labels: true
